---
prometheus_max_size: 100GB

# will be monitoring port 9100
federate_host_exporters:
  - host: rpi
    domain: 'ds'
    services:
      - homebridge
      - cups
  - host: rlyeh
    domain: 'ds'
    services:
      - ssh
      - strongswan-starter
      - snap.lxd.daemon
      - haproxy
  - host: ulthar
    domain: 'ds'
    services:
      - ssh
      - strongswan-starter
      - snap.lxd.daemon
  - host: rundeck
    domain: 'rlyeh.ds'
    services:
      - rundeckd
  - host: grafana
    domain: 'rlyeh.ds'
    services:
      - grafana-server
  - host: intranet
    domain: 'rlyeh.ds'
    services:
      - authelia
      - nginx
  - host: prom01
    domain: 'rlyeh.ds'
    services:
      - prometheus
      - prometheus-alertmanager
  - host: loki01
    domain: 'rlyeh.ds'
    services:
      - loki
  - host: ppp
    domain: 'rlyeh.ds'
    services:
      - pocket-plus-plus
  - host: jjit
    domain: 'rlyeh.ds'
    services:
      - sshd
  - host: smi
    domain: 'rlyeh.ds'
    services:
      - SimpleMachineInventory
  - host: webd01
    domain: 'rlyeh.ds'
    services:
      - php{{ php_ver }}-fpm
      - nginx
      - memcached_blog
      - memcached_foto
  - host: webd02
    domain: 'rlyeh.ds'
    services:
      - php{{ php_ver }}-fpm
      - nginx
      - memcached_blog
      - memcached_foto
  - host: webd03
    domain: 'ulthar.ds'
    services:
      - php{{ php_ver }}-fpm
      - nginx
      - memcached_blog
      - memcached_foto
  - host: webm01
    domain: 'rlyeh.ds'
    services:
      - php{{ php_ver }}-fpm
      - nginx
  - host: mysql01
    domain: 'rlyeh.ds'
    services:
      - mariadb
  - host: mysql02
    domain: 'rlyeh.ds'
    services:
      - mariadb
  - host: mysql03
    domain: 'rlyeh.ds'
    services:
      - mariadb
  - host: mysql04
    domain: 'ulthar.ds'
    services:
      - mariadb
  - host: psql01
    domain: 'rlyeh.ds'
    services:
      - patroni
      - etcd
  - host: psql02
    domain: 'rlyeh.ds'
    services:
      - patroni
      - etcd
  - host: psql03
    domain: 'rlyeh.ds'
    services:
      - patroni
      - etcd
  - host: psql04
    domain: 'ulthar.ds'
    services:
      - patroni
      - etcd
  - host: psql05
    domain: 'ulthar.ds'
    services:
      - patroni
      - etcd
  - host: influx01
    domain: 'rlyeh.ds'
    services:
      - influxdb
  - host: redis01
    domain: 'rlyeh.ds'
    services:
      - redis-server
      - redis-sentinel
  - host: redis02
    domain: 'rlyeh.ds'
    services:
      - redis-server
      - redis-sentinel
  - host: redis03
    domain: 'rlyeh.ds'
    services:
      - redis-server
      - redis-sentinel
  - host: redis04
    domain: 'ulthar.ds'
    services:
      - redis-server
      - redis-sentinel
  - host: dns01
    domain: 'rlyeh.ds'
    services:
      - named
  - host: dns02
    domain: 'rlyeh.ds'
    services:
      - named
  - host: dns03
    domain: 'ulthar.ds'
    services:
      - named
  - host: zarcioplan
    domain: 'rlyeh.ds'
    services:
      - zarcioplan
# more detailed version of federate_host_exporters
federate_other_exporters:
  - host: mysql01
    domain: 'rlyeh.ds'
    type: mysql
    port: 9104
  - host: mysql02
    domain: 'rlyeh.ds'
    type: mysql
    port: 9104
  - host: mysql03
    domain: 'rlyeh.ds'
    type: mysql
    port: 9104
  - host: mysql04
    domain: 'ulthar.ds'
    type: mysql
    port: 9104
#  - host: psql02
#    domain: 'rlyeh.ds'
#    type: psql
#    port: 9187
#  - host: psql03
#    domain: 'rlyeh.ds'
#    type: psql
#    port: 9187
#  - host: psql01
#    domain: 'rlyeh.ds'
#    type: psql
#    port: 9187
  - host: psql01
    domain: 'rlyeh.ds'
    type: patroni
    port: 9547
  - host: psql02
    domain: 'rlyeh.ds'
    type: patroni
    port: 9547
  - host: psql03
    domain: 'rlyeh.ds'
    type: patroni
    port: 9547
  - host: psql04
    domain: 'ulthar.ds'
    type: patroni
    port: 9547
  - host: psql05
    domain: 'ulthar.ds'
    type: patroni
    port: 9547
  - host: webd01
    domain: 'rlyeh.ds'
    type: nginx
    port: 9113
  - host: webm01
    domain: 'rlyeh.ds'
    type: nginx
    port: 9113
  - host: intranet
    domain: 'rlyeh.ds'
    type: nginx
    port: 9113
  - host: rlyeh
    domain: 'rlyeh.ds'
    type: haproxy
    port: 8404


duplicati_monitored: 
  - alias: webd01_blog
    max_delay: 1
    dropbox_path: /rlyeh/webd01/srv/blog/
    job_id: webd01__srv_blog_
  - alias: webd01_foto
    max_delay: 1
    dropbox_path: /rlyeh/webd01/srv/foto2/
    job_id: webd01__srv_foto2_
  - alias: webm01
    max_delay: 1
    dropbox_path: /rlyeh/webm01/srv/madzia/
    job_id: webm01__srv_madzia_
  - alias: loki01
    max_delay: 1
    dropbox_path: /rlyeh/loki01/srv/loki/
    job_id: loki01__srv_loki_
  - alias: influx01
    max_delay: 1
    dropbox_path: /rlyeh/influx01/var/lib/influxdb/
    job_id: influx01__var_lib_influxdb_
  - alias: prom01
    max_delay: 1
    dropbox_path: /rlyeh/prom01/var/lib/prometheus/
    job_id: prom01__var_lib_prometheus_
  - alias: psql02
    max_delay: 1
    dropbox_path: /rlyeh/psql02/var/lib/postgresql/
    job_id: psql02__var_lib_postgresql_
  - alias: mysql02
    max_delay: 1
    dropbox_path: /rlyeh/mysql02/var/lib/mysql/
    job_id: mysql02__var_lib_mysql_


