---
prometheus_max_size: 100GB

# will be monitoring port 9100
federate_host_exporters:
  - host: hv
    services:
      - ssh
      - strongswan-starter
      - snap.lxd.daemon
      - haproxy
  - host: semaphore
    services:
      - semaphore
  - host: grafana
    services:
      - grafana-server
  - host: intranet
    services:
      - authelia
      - nginx
  - host: prom01
    services:
      - prometheus
      - prometheus-alertmanager
  - host: loki01
    services:
      - loki #???
  - host: ppp
    services:
      - pocket-plus-plus
  - host: smi
    services:
      - SimpleMachineInventory
  - host: webd01
    services:
      - php8.0-fpm
      - nginx
      - memcached_blog
      - memcached_foto
  - host: webd02
    services:
      - php8.0-fpm
      - nginx
      - memcached_blog
      - memcached_foto
  - host: webm01
    services:
      - php8.0-fpm
      - nginx
  - host: mysql01
    services:
      - mariadb
  - host: mysql02
    services:
      - mariadb
  - host: mysql03
    services:
      - mariadb
  - host: psql01
    services:
      - patroni
      - etcd
  - host: psql02
    services:
      - patroni
      - etcd
  - host: psql03
    services:
      - patroni
      - etcd
  - host: influx01
    services:
      - influxdb
  - host: rpi
    services:
      - minidlna
      - smbd
  - host: redis01
    services:
      - redis-server
      - redis-sentinel
  - host: redis02
    services:
      - redis-server
      - redis-sentinel
  - host: redis03
    services:
      - redis-server
      - redis-sentinel
  - host: dns01
    services:
      - named
  - host: dns02
    services:
      - named
# more detailed version of federate_host_exporters
federate_other_exporters: 
#  - host: mysql02
#    type: mysql
#    port: 9104
#  - host: mysql03
#    type: mysql
#    port: 9104
#  - host: mysql01
#    type: mysql
#    port: 9104
#  - host: psql02
#    type: psql
#    port: 9187
#  - host: psql03
#    type: psql
#    port: 9187
#  - host: psql01
#    type: psql
#    port: 9187
#  - host: webd01
#    type: nginx
#    port: 9113
#  - host: webm01
#    type: nginx
#    port: 9113
#  - host: intranet
#    type: nginx
#    port: 9113
  - host: hv
    type: haproxy
    port: 8404

duplicati_monitored_jobs: [] #TBD
monitored_duplicati_dropbox_paths: [] #TBD