---
- name: install nginx
  ansible.builtin.apt:
    name: nginx-full
- name: Default nginx opts
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: /etc/nginx/{{ item }}
    mode: 0744
  with_items:
    - default_https_opts.conf
    - access_log.conf
