---
- hosts: rlyeh
  tasks:
    - name: fix_masquerade.sh deploy
      ansible.builtin.template:
        src: hv_generic/fix_masquerade.sh
        dest: /opt/fix_masquerade.sh
        mode: 0555
    - name: fix_masquerade.sh cron
      ansible.builtin.cron:
        name: /opt/fix_masquerade.sh
        minute: "*"
        hour: "*"
        job: /opt/fix_masquerade.sh 1>/dev/null 2>/dev/null

    - name: charon-logging.conf
      ansible.builtin.template:
        src: rlyeh/charon-logging.conf
        dest: /etc/strongswan.d/charon-logging.conf

    - name: ipsec.conf
      ansible.builtin.template:
        src: rlyeh/ipsec.conf
        dest: /etc/ipsec.conf

    - name: ipsec.secrets
      ansible.builtin.template:
        src: ../scloud-secrets/plain/ipsec_rlyeh/ipsec.secrets
        dest: /etc/ipsec.secrets

    - name: restart ipsec
      ansible.builtin.systemd:
        service: ipsec
        state: restarted

    - name: xl2tpd.conf
      ansible.builtin.template:
        src: rlyeh/xl2tpd.conf
        dest: /etc/xl2tpd/xl2tpd.conf
    - name: options.xl2tpd
      ansible.builtin.template:
        src: rlyeh/options.xl2tpd
        dest: /etc/ppp/options.xl2tpd
    - name: chap-secrets
      ansible.builtin.template:
        src: ../scloud-secrets/plain/ipsec_rlyeh/chap-secrets
        dest: /etc/ppp/chap-secrets

    - name: restart xl2tpd
      ansible.builtin.systemd:
        service: xl2tpd
        state: restarted
