---
- hosts: rlyeh
  tasks:
    - name: fix_masquerade.sh deploy
      ansible.builtin.template:
        src: hv_generic/fix_masquerade.sh
        dest: /opt/fix_masquerade.sh
        mode: 0555
    - name: fix_masquerade.sh cron
      ansible.builtin.cron:
        name: /opt/fix_masquerade.sh
        minute: "*"
        hour: "*"
        job: /opt/fix_masquerade.sh 1>/dev/null 2>/dev/null

    - name: ipsec.conf
      ansible.builtin.template:
        src: rlyeh/ipsec.conf
        dest: /etc/ipsec.conf

    - name: ipsec.secrets
      ansible.builtin.template:
        src: ../scloud-secrets/plain/ipsec_rlyeh/ipsec.secrets
        dest: /etc/ipsec.secrets

    - name: restart ipsec
      ansible.builtin.systemd:
        service: ipsec
        state: restarted
