---
- hosts: rlyeh
  tasks:
    - name: SSL dir
      ansible.builtin.file:
        state: directory
        path: /etc/haproxy/ssl/
        mode: 0700
        owner: root
    - name: Deploy certs
      ansible.builtin.copy:
        src: ../scloud-secrets/plain/daniel.pem
        dest: /etc/haproxy/ssl/daniel.pem

    - name: configure
      ansible.builtin.template:
        src: haproxy/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg

    - name: restart
      ansible.builtin.systemd:
        service: haproxy
        state: restarted
        enabled: true
