---
- hosts: rlyeh
  tasks:
    - name: error pages
      ansible.builtin.template:
        src: haproxy/error.http
        dest: /etc/haproxy/errors/{{ item.error_code }}.http
      with_items: "{{ http_codes }}"
