---
- hosts: webd0x_primary
  tasks:
    - name: blog - deploy wordpress db error page
      ansible.builtin.template:
        src: webd/db-error.php
        dest: /srv/blog/wp-content/db-error.php
      with_items:
        - error_code: 503
          error_name: Service Temporarily Unavailable
          error_explanation: Database error.
    - name: foto - deploy wordpress db error page
      ansible.builtin.template:
        src: webd/db-error.php
        dest: /srv/foto2/wp-content/db-error.php
      with_items:
        - error_code: 503
          error_name: Service Temporarily Unavailable
          error_explanation: Database error.

- hosts: webd0x
  tasks:
    - name: global error pages - dir
      ansible.builtin.file:
        state: directory
        path: /srv/errors/error/
        owner: www-data
        group: www-data
        mode: 0770
        recurse: true
    - name: global error pages
      ansible.builtin.template:
        src: error.html
        dest: /srv/errors/error/{{ item.error_code }}.html
      with_items: "{{ http_codes }}"
