---
- hosts: mysql02  # this must be single operator node
  vars:
  tasks:

    - name: create web suite dbs
      community.mysql.mysql_db:
        name: "{{ item.name }}"
        state: present
        login_password: "{{ mysql_root }}"
        login_user: root
        login_host: "10.0.2.2"
      with_items: "{{ mysql_dbs.values() }}"
      no_log: true

    - name: create web suite users and grant them access
      community.mysql.mysql_user:
        name: "{{ item.user }}"
        password: "{{ item.pass }}"
        host: '10.%'
        priv: "{{ item.name }}.*:ALL"
        state: present
        login_password: "{{ mysql_root }}"
        login_user: root
        login_host: "10.0.2.2"
      with_items: "{{ mysql_dbs.values() }}"
      no_log: true

    - name: create exporter user
      community.mysql.mysql_user:
        name: exporter
        password: "{{ mysql_exporter }}"
        host: '127.0.0.1'
        state: present
        login_password: "{{ mysql_root }}"
        login_user: root
        login_host: "10.0.2.2"
    - name: grant exporter specific privileges
      community.mysql.mysql_query:
        login_host: "10.0.2.2"
        login_user: root
        login_password: '{{ mysql_root }}'
        query: GRANT PROCESS, REPLICATION CLIENT, SLAVE MONITOR, SELECT ON *.* TO 'exporter'@'127.0.0.1';
