---
- hosts: psql01 psql02 psql03 psql04 psql05
  tasks:
    - name: /etc/default/etcd
      ansible.builtin.template:
        src: psql/etcd
        dest: /etc/default/etcd
    - name: etcd restart
      ansible.builtin.systemd:
        name: etcd
        state: restarted
        enabled: true

    - name: /etc/patroni/config.yml
      ansible.builtin.template:
        src: psql/patroni.yml.j2
        dest: /etc/patroni/config.yml
    - name: disable default postgres instance
      ansible.builtin.systemd:
        name: postgresql
        state: stopped
        enabled: false
    - name: restart patroni
      ansible.builtin.systemd:
        name: patroni
        state: restarted
        enabled: true

    - name: haproxy.cfg
      ansible.builtin.template:
        src: psql/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
    - name: haproxy restart
      ansible.builtin.systemd:
        name: haproxy
        state: restarted

    - name: check
      ansible.builtin.shell: patronictl -d etcd://127.0.0.1:2379 list patroni_psql0x
