---
- hosts: influx01
  tasks:

    - name: create influx dbs
      community.general.influxdb_database:
        database_name: '{{ item.name }}'
        state: present
        login_username: '{{ influx_admin_user }}'
        login_password: '{{ influx_admin_pass }}'
      with_items: "{{ influx_dbs.values() }}"
      no_log: true

    - name: grant access to db dedicated users
      community.general.influxdb_user:
        user_name: '{{ item.user }}'
        user_password: '{{ item.pass }}'
        login_username: '{{ influx_admin_user }}'
        login_password: '{{ influx_admin_pass }}'
        grants:
          - database: '{{ item.name }}'
            privilege: 'WRITE'
      with_items: "{{ influx_dbs.values() }}"
      no_log: true

    - name: grant grafana read access everywhere
      community.general.influxdb_user:
        user_name: '{{ influx_grafana_user }}'
        user_password: '{{ influx_grafana_pass }}'
        login_username: '{{ influx_admin_user }}'
        login_password: '{{ influx_admin_pass }}'
        grants:
          - database: '{{ item.name }}'
            privilege: 'READ'
      with_items: "{{ influx_dbs.values() }}"
      no_log: true
