---
- hosts: influx01
  tasks:
    - name: cfg
      ansible.builtin.template:
        src: influx/influxdb.conf
        dest: /etc/influxdb/influxdb.conf

    - name: restart
      ansible.builtin.systemd:
        name: influxdb
        state: restarted
