---
- hosts: influx01
  roles:
    - basic
    - prom-monitored
  tasks:
    - name: package
      ansible.builtin.apt:
        name:
          - influxdb={{ influxdb_version }}
          - influxdb-client={{ influxdb_version }}
    - name: restart
      ansible.builtin.systemd:
        name: influxdb
        state: restarted
