---
- hosts: smi
  tasks:
    - name: Deploy SimpleMachineInventory config
      ansible.builtin.template:
        src: smi/SimpleMachineInventory.config.yml
        dest: /srv/SimpleMachineInventory/config.yml
        mode: '0755'
    - name: Restart service
      ansible.builtin.service:
        name: SimpleMachineInventory
        state: restarted
