---
- hosts: rundeck
  tasks:
    - name: stop
      ansible.builtin.systemd:
        name: rundeckd
        state: stopped
    - name: nuke
      ansible.builtin.file:
        path: /var/lib/rundeck/
        state: absent
    - name: install
      ansible.builtin.get_url:
        url: https://packagecloud.io/pagerduty/rundeck/packages/any/any/rundeck_{{ rundeck_ver }}_all.deb/download.deb
        dest: /tmp/rundeck.deb
        mode: 0400
    - name: install
      ansible.builtin.shell: dpkg --force-confold -i /tmp/rundeck.deb
    - name: enable
      ansible.builtin.systemd:
        name: rundeckd
        state: restarted
        enabled: true
    - name: reboot
      ansible.builtin.reboot:
