---
- hosts: rundeck
  tasks:
    - name: install
      ansible.builtin.get_url:
        url: https://packagecloud.io/pagerduty/rundeck/packages/any/any/rundeck_{{ rundeck_ver }}_all.deb/download.deb
        dest: /tmp/rundeck.deb
        mode: 0400
    - name: install
      ansible.builtin.shell: dpkg --force-confold -i /tmp/rundeck.deb
    - name: enable
      ansible.builtin.systemd:
        name: rundeckd
        state: restarted
        enabled: true
    - name: reboot
      ansible.builtin.reboot:
