---
- hosts: smi
  vars:
    remote: git@github.com:skowronski-cloud/simplemachineinventory.git
    path: /srv/SimpleMachineInventory
  tasks:
    - name: safe dir
      shell: git config --global --add safe.directory "{{ path }}"
    - name: Deploy SimpleMachineInventory
      ansible.builtin.git:
        repo: "{{ remote }}"
        dest: "{{ path }}"
        key_file: "{{ deploy_key }}"
        accept_hostkey: true
        force: true
    - name: Deploy SimpleMachineInventory dependencies
      ansible.builtin.pip:
        requirements: "{{ path }}/requirements.txt"
        executable: pip3
    - name: Deploy service file
      ansible.builtin.file:
        state: link
        src: "{{ path }}/SimpleMachineInventory.service"
        dest: /lib/systemd/system/SimpleMachineInventory.service
    - name: Deploy service file
      shell: systemctl daemon-reload

    - name: Deploy SimpleMachineInventory config
      ansible.builtin.template:
        src: smi/SimpleMachineInventory.config.yml
        dest: "{{ path }}/config.yml"
        mode: '0755'
    - name: Enable service
      ansible.builtin.service:
        name: SimpleMachineInventory
        state: restarted
        enabled: true
