---
- hosts: rundeck
  tasks:
    - name: configure basics
      ansible.builtin.template:
        src: rundeck/rundeck-config.properties
        dest: /etc/rundeck/rundeck-config.properties
        mode: 0400
    - name: configure realm
      ansible.builtin.template:
        src: rundeck/realm.properties
        dest: /etc/rundeck/realm.properties
        mode: 0400
    - name: enable
      ansible.builtin.systemd:
        name: rundeckd
        state: restarted
        enabled: true

    - name: guard preauthenticated rundeck instance
      community.general.ufw:
        state: enabled
        policy: allow
    - name: guard preauthenticated rundeck instance
      community.general.ufw:
        rule: deny
        port: 4440
    - name: guard preauthenticated rundeck instance
      community.general.ufw:
        rule: allow
        port: 4440
        src: 10.0.8.1
        insert: 1
