---
- name: intranet deploy part 1 - app artifacts
  hosts: intranet
  tasks:
    - name: Prepare dirs
      ansible.builtin.file:
        path: /srv/{{ item }}
        state: directory
        mode: 0744
      with_items:
        - skowronski.cloud
        - keys

    - name: Deploy internal__skowronski.cloud
      ansible.builtin.git:
        repo: git@github.com:skowronski-cloud/skowronski.cloud.git
        dest: /srv/skowronski.cloud/
        key_file: "{{ deploy_key }}"
        accept_hostkey: true
        force: true

    - name: Deploy skowronski.cloud submodules
      ansible.builtin.shell:
        chdir: /srv/skowronski.cloud
        cmd: GIT_SSH_COMMAND='ssh -i {{ deploy_key }}'  /usr/bin/git submodule update --recursive --remote --force

    - name: Run get_dict.sh
      ansible.builtin.shell:
        chdir: /srv/skowronski.cloud/random
        cmd: ./get_dict.sh

    - name: mandatory fixing permissions
      ansible.builtin.file:
        path: /srv
        owner: www-data
        recurse: true
