---
- hosts: ppp
  tasks:
    - name: Deploy pocket-plus-plus
      ansible.builtin.git:
        repo: git@github.com:danielskowronski/pocket-plus-plus.git
        dest: /srv/pocket-plus-plus
        key_file: "{{ deploy_key }}"
        accept_hostkey: true
        force: true
    - name: Deploy pocket-plus-plus dependencies
      ansible.builtin.pip:
        requirements: /srv/pocket-plus-plus/requirements.txt
        executable: pip3
    - name: Deploy service file
      ansible.builtin.template:
        src: ppp/pocket-plus-plus.service
        dest: /lib/systemd/system/pocket-plus-plus.service
    - name: Deploy service file
      ansible.builtin.shell: systemctl daemon-reload
    - name: Enable service
      ansible.builtin.service:
        name: pocket-plus-plus
        state: restarted
        enabled: true
