---
- name: intranet deploy part 1 - app artifacts
  hosts: intranet
  vars:
    remote: git@github.com:skowronski-cloud/skowronski.cloud.git
    path: /srv/skowronski.cloud/
  tasks:
    - name: Prepare dirs
      ansible.builtin.file:
        path: /srv/{{ item }}
        state: directory
        mode: 0744
      with_items:
        - skowronski.cloud
        - keys

    - name: safe dir
      shell: git config --global --add safe.directory "{{ path }}"
    - name: Deploy internal__skowronski.cloud
      ansible.builtin.git:
        repo: "{{ remote }}"
        dest: "{{ path }}"
        key_file: "{{ deploy_key }}"
        accept_hostkey: true
        force: true

    - name: Deploy skowronski.cloud submodules
      ansible.builtin.shell:
        chdir: "{{ path }}"
        cmd: GIT_SSH_COMMAND='ssh -i {{ deploy_key }}' /usr/bin/git submodule update --recursive --remote --force

    - name: Run get_dict.sh
      ansible.builtin.shell:
        chdir: "{{ path }}/random"
        cmd: ./get_dict.sh

    - name: mandatory fixing permissions
      ansible.builtin.file:
        path: /srv
        owner: www-data
        recurse: true
