---
- hosts: intranet
  tasks:
    - name: fetch authelia binary
      ansible.builtin.unarchive:
        src: https://github.com/authelia/authelia/releases/download/{{ authelia_ver }}/authelia-{{ authelia_ver }}-linux-amd64.tar.gz
        remote_src: true
        dest: /srv/authelia
    - name: fetch authelia html
      ansible.builtin.unarchive:
        src: https://github.com/authelia/authelia/releases/download/{{ authelia_ver }}/authelia-{{ authelia_ver }}-public_html.tar.gz
        remote_src: true
        dest: /srv/authelia

    - name: Enable and start systemd service - authelia
      ansible.builtin.systemd:
        name: authelia
        daemon_reload: true
        state: restarted
        enabled: true
