---
- name: grafana dashboard
  vars:
    remote: git@github.com:skowronski-cloud/graphs
    path: /srv/graphs.skowronski.cloud
  hosts: grafana
  tasks:
    - name: safe dir
      shell: git config --global --add safe.directory "{{ path }}"
    - name: Deploy graphs.skowronski.cloud
      ansible.builtin.git:
        repo: "{{ remote }}"
        dest: "{{ path }}"
        key_file: "{{ deploy_key }}"
        accept_hostkey: true
        force: true
    - name: Import Dashboards
      community.grafana.grafana_dashboard:
        grafana_url: http://grafana.rlyeh.ds:3000
        grafana_user: "{{ grafana_admin_user }}"
        grafana_password: "{{ grafana_admin_pass }}"
        state: present
        commit_message: Updated by ansible
        overwrite: true
        path: /srv/graphs.skowronski.cloud/grafana-dashboard.json
        uid: zBlCiep7z

- name: intranet graphs proxy
  vars:
    remote: git@github.com:skowronski-cloud/graphs
    path: /srv/graphs
  hosts: intranet
  tasks:
    - name: Prepare dirs
      ansible.builtin.file:
        path: /srv/graphs
        state: directory
        mode: 0744

    - name: safe dir
      shell: git config --global --add safe.directory "{{ path }}"
    - name: Deploy graphs.skowronski.cloud
      ansible.builtin.git:
        repo: "{{ remote }}"
        dest: "{{ path }}"
        key_file: "{{ deploy_key }}"
        accept_hostkey: true
        force: true

    - name: Add cron
      ansible.builtin.cron:
        hour: "*"
        minute: "*"
        job: /bin/bash -c 'cd /srv/graphs/; bash grafana-proxy.sh grafana.rlyeh.ds {{ grafana_readonly_token }}'
        name: graphs

    - name: chmod
      ansible.builtin.file:
        path: /srv/graphs
        state: directory
        mode: 0774
        owner: www-data
        group: www-data
