---
- hosts: prom01
  tasks:
    - name: prometheus federate config
      ansible.builtin.template:
        src: prom/prometheus_federate.yml.j2
        dest: /etc/prometheus/prometheus.yml
    - name: prometheus alert rules
      ansible.builtin.template:
        src: prom/prom.rules
        dest: /etc/prometheus/rules/prom.rules
    - name: prometheus restart
      ansible.builtin.systemd:
        name: prometheus
        state: restarted

    - name: prometheus-alertmanager config
      ansible.builtin.template:
        src: prom/alertmanager.yml.j2
        dest: /etc/prometheus/alertmanager.yml
    - name: prometheus-alertmanager restart
      sansible.builtin.ystemd:
        name: prometheus-alertmanager
        state: restarted
