---
#- hosts: hv
#  vars:
#    containers:
#      - redis11
#      - redis12
#      - redis13
#  tasks:
#    - name: spin up LXD container
#      ansible.builtin.include_tasks: common_lxdct.yml
#      with_items: '{{containers}}'


- name: redis
  hosts: redis1x
  roles:
#    - basic
  tasks:
    - name: install
      apt:
        name: redis-server
      ignore_errors: true
    - name: firewall - main protocol
      ufw:
        rule: allow
        port: 6379
    - name: firewall - cluster bus 
      ufw:
        rule: allow
        port: 16379
    - name: config
      template:
        src: devredis/redis.conf
        dest: /etc/redis/redis.conf
    - name: restart
      systemd:
        service: redis
        state: restarted
      throttle: 1

- name: sentinel
  hosts: redis1x
  tasks:
    - name: firewall - sentinel
      ufw:
        rule: allow
        port: 26379
    - name: config
      template:
        src: devredis/sentinel.conf
        dest: /etc/redis/sentinel.conf
    - name: service file fix
      template:
        src: devredis/sentinel.service
        dest: /lib/systemd/system/redis-sentinel.service
    - name: install
      apt:
        name: redis-sentinel
      ignore_errors: true
    - name: libsystemd-dev
      apt:
        name: libsystemd-dev
    - name: restart
      systemd:
        service: redis-sentinel
        state: restarted
        daemon_reload: true