---
- name: redis
  hosts: redis0x
  tasks:
    - name: install
      ansible.builtin.apt:
        name: redis-server
    - name: firewall - main protocol
      community.general.ufw:
        rule: allow
        port: 6379
    - name: firewall - cluster bus
      community.general.ufw:
        rule: allow
        port: 16379
    - name: config
      ansible.builtin.template:
        src: redis/redis.conf
        dest: /etc/redis/redis.conf
    - name: certs
      ansible.builtin.template:
        src: ../scloud-secrets/plain/{{ item }}
        dest: /etc/redis/{{ item }}
      with_items:
        - redis.crt
        - redis.key
        - DS_CA.crt
    - name: restart
      ansible.builtin.systemd:
        service: redis
        state: restarted
      throttle: 1

- name: sentinel
  hosts: redis0x
  tasks:
    - name: install
      ansible.builtin.apt:
        name: redis-sentinel
    - name: libsystemd-dev
      ansible.builtin.apt:
        name: libsystemd-dev
    - name: firewall - sentinel
      ansible.builtin.ufw:
        rule: allow
        port: 26379
    - name: config
      ansible.builtin.template:
        src: redis/sentinel.conf
        dest: /etc/redis/sentinel.conf
    - name: service file fix
      ansible.builtin.template:
        src: redis/sentinel.service
        dest: /lib/systemd/system/redis-sentinel.service
    - name: restart
      ansible.builtin.systemd:
        service: redis-sentinel
        state: restarted
        daemon_reload: true
