---
- name: redis
  hosts: redis0x
  roles:
    - role: v0112358.redis_cluster
      vars:
        tags: redis0x
        apt_repository_codename: hirsute
        unprivileged_container: true
  tasks:
    - name: firewall - main protocol
      ufw:
        rule: allow
        port: 6379
    - name: firewall - cluster bus 
      ufw:
        rule: allow
        port: 16379
    - name: config
      lineinfile:
        line: include /etc/redis/custom.conf
        path: /etc/redis/redis.conf
    - name: config
      template:
        src: redis/redis.conf
        dest: /etc/redis/custom.conf
    - name: certs
      template:
        src: ../rlyeh-secrets/plain/{{item}}
        dest: /etc/redis/{{item}}
      with_items:
        - redis.crt
        - redis.key
        - DS_CA.crt
    - name: restart
      systemd:
        service: redis
        state: restarted
      throttle: 1

- name: join cluster
  hosts: redis0x_slaves
  tasks:
    - name: add-node
      shell: echo yes | redis-cli --tls --cluster add-node {{ ansible_fqdn }}:6379 {{ redis_master_ip }}:6379 --cluster-slave --pass {{ redis_admin_pass }}
      ignore_errors: true

- name: fix cluster
  hosts: redis0x_master
  tasks:
    - name: add-node
      shell: echo yes | redis-cli --tls --cluster fix {{ redis_master }}.rlyeh.ds:6379 --pass {{ redis_admin_pass }}
      no_log: true

- name: sentinel
  hosts: redis0x
  tasks:
    - name: install
      apt:
        name: redis-sentinel
    - name: libsystemd-dev
      apt:
        name: libsystemd-dev
    - name: firewall - sentinel
      ufw:
        rule: allow
        port: 26379
    - name: config
      template:
        src: redis/sentinel.conf
        dest: /etc/redis/sentinel.conf
    - name: service file fix
      template:
        src: redis/sentinel.service
        dest: /lib/systemd/system/redis-sentinel.service
    - name: restart
      systemd:
        service: redis-sentinel
        state: restarted
        daemon_reload: true