---

- hosts: localhost
  tasks:
    - name: Create a 5 minute maintenance window for all services
      community.general.pagerduty:
        token: "{{ pagerduty_token }}"
        hours: 0
        minutes: 5
        state: running
        service: PCD36HD,P8O29QM,P12T7M9,PRI64DA,P7ZX3OK,PVUU5T0,PN3QFWK,P6JPU8O,POKQN3P,P2POYAK,PZFNP7S,PGPR7X3
        requester_id: PIESNXM

- hosts: az3
  tasks:
    - name: shutdown az3
      community.general.shutdown:
      throttle: 1
- hosts: az2
  tasks:
    - name: shutdown az2
      community.general.shutdown:
      throttle: 1
- hosts: localhost
  tasks:
    - name: confirm rebooting rlyeh hv - including az1
      pause:
        prompt: Press return to continue. Press Ctrl+c and then "a" to abort
- hosts: rlyeh
  tasks:
    - name: reboot
      reboot:
