---
- hosts: rlyeh
  tasks:
    - name: bootup az3
      ansible.builtin.shell: lxc start {{ item }}
      with_items: "{{ groups['az3'] }}"
      throttle: 1
      ignore_errors: true
    - name: bootup az2
      ansible.builtin.shell: lxc start {{ item }}
      with_items: "{{ groups['az2'] }}"
      throttle: 1
      ignore_errors: true
    - name: bootup az1
      ansible.builtin.shell: lxc start {{ item }}
      with_items: "{{ groups['az1'] }}"
      throttle: 1
      ignore_errors: true
    - name: bootup az0
      ansible.builtin.shell: lxc start {{ item }}
      with_items: "{{ groups['az0'] }}"
      throttle: 1
      ignore_errors: true
