---
# see https://lxd.readthedocs.io/en/latest/instances/
- name: Deploy Containers
  community.general.lxd_container:
    name: '{{ item }}'  # with_items from parent playbook
    state: started
    source: '{{ lxd_source }}'  # from group_vars/all.yml
    config:
      limits.cpu: '{{ hostvars[item].cpu }}'
      limits.memory: '{{ hostvars[item].mem }}MB'
      security.nesting: '{{ hostvars[item].lxd_nesting | default ("false") }}'
      security.privileged: '{{ hostvars[item].lxd_privileged | default ("false") }}'
    devices:
      root:
        path: /
        pool: default
        size: '{{ hostvars[item].dsk }}GB'
        type: disk
      eth0:
        type: nic
        nictype: bridged
        parent: '{{ lxd_network.bridge }}'
        ipv4.address: '{{ hostvars[item].ansible_host }}'
        host_name: '{{ item }}'
    wait_for_ipv4_addresses: true
    timeout: 600
  register: lxd_container

- name: Preconfigure Containers - DNS 1/2
  ansible.builtin.shell: lxc exec {{ item }}  -- sh -c 'echo "[Resolve]\nDNS=1.1.1.1" > /etc/systemd/resolved.conf'
- name: Preconfigure Containers - DNS 2/2
  ansible.builtin.shell: lxc exec {{ item }}  -- sh -c 'systemctl restart systemd-resolved'
- name: Preconfigure Containers - IPv6 1/2
  ansible.builtin.shell: lxc exec {{ item }}  -- sh -c '/usr/sbin/sysctl -w net.ipv6.conf.all.disable_ipv6=1'
- name: Preconfigure Containers - IPv6 2/2
  ansible.builtin.shell: lxc exec {{ item }}  -- sh -c '/usr/sbin/sysctl -w net.ipv6.conf.all.disable_ipv6=1'
- name: Preconfigure Containers - OpenSSH server
  ansible.builtin.shell: lxc exec {{ item }}  -- sh -c '/usr/bin/apt -y install openssh-server'
- name: Preconfigure Containers - ssh key 1/4
  ansible.builtin.shell: lxc exec {{ item }}  -- sh -c '/bin/mkdir -p /root/.ssh'
- name: Preconfigure Containers - ssh key 2/4
  ansible.builtin.shell: lxc exec {{ item }}  -- sh -c '/bin/chmod 0700 /root/.ssh'
- name: Preconfigure Containers - ssh key 3/4
  ansible.builtin.shell: lxc exec {{ item }}  -- sh -c '/bin/echo {{ master_ssh_key }} >> /root/.ssh/authorized_keys'
- name: Preconfigure Containers - ssh key 4/4
  ansible.builtin.shell: lxc exec {{ item }}  -- sh -c '/bin/chmod 0600 /root/.ssh/authorized_keys'
