#!/bin/bash

ansible-playbook -i _inventory.py --extra-vars "@../scloud-secrets/plain/ansible_vars.yml" $@ 
#ansible-playbook -i inventory.bootstrap.txt --extra-vars "@../scloud-secrets/plain/ansible_vars.yml" $@ 
