---
- name: fetch promtail binary
  ansible.builtin.unarchive:
    src: https://github.com/grafana/loki/releases/download/{{ loki_ver }}/promtail-linux-{{ cpu_arch }}.zip
    remote_src: true
    dest: /usr/local/bin/
- name: deploy config file
  ansible.builtin.template:
    src: promtail.yml.j2
    dest: /etc/promtail.yml
    mode: 0744
- name: deploy service file
  ansible.builtin.template:
    src: promtail.service
    dest: /lib/systemd/system/promtail.service
    mode: 0744
- name: enable service
  ansible.builtin.systemd:
    name: promtail.service
    state: started
    enabled: true
