---
- name: dns_client | service
  ansible.builtin.systemd:
    name: systemd-resolved
    state: stopped
    enabled: false

- name: dns_client | prepare resolvers list for normal hosts
  ansible.builtin.set_fact:
    resolvers: "nameserver {{ resolvers_order[ hv ] | join('\nnameserver ') }}"
  when: "'dns0x' not in group_names"

- name: dns_client | prepare resolvers list for dns0x
  ansible.builtin.set_fact:
    resolvers: "nameserver 1.1.1.1"
  when: "'dns0x' in group_names"

- name: dns_client | /etc/resolv.conf
  ansible.builtin.file:
    state: file
    path: /etc/resolv.conf
    owner: root
    group: root
    mode: 0744

- name: dns_client | /etc/resolv.conf
  ansible.builtin.copy:
    dest: /etc/resolv.conf
    content: |
      {{ resolvers }}
      search {{ search_domains }}
