---
- name: Create special ssh key dir
  file:
    path: /srv/keys
    state: directory
    mode: '0700'
- name: Deploy special ssh key
  copy:
    src: ../rlyeh-secrets/plain/{{ item }}
    dest: /srv/keys/{{ item }}
    mode: '0600'
  with_items:
    - danielskowronski-internal-git__rsa
    - danielskowronski-internal-git__rsa.pub