---
- name: /etc/systemd/resolved.conf
  template:
    src: resolved.conf 
    dest: /etc/systemd/resolved.conf
- name: restart systemd-resolved
  systemd:
    name: systemd-resolved
    state: restarted
