---
- name: /var/log/journal/
  ansible.builtin.file:
    path: /var/log/journal/
    state: directory
    mode: 0744
  notify: setup journald
- name: use persisten storage
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    line: Storage=persistent
  notify: reload journald
- name: max storage used
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    line: SystemMaxUse={{ journald_maxuse }}
  notify: reload journald
