---
- name: Mirror fix
  ansible.builtin.template:
    src: sources.list
    dest: /etc/apt/sources.list
    mode: 0744
- name: Install base packages
  ansible.builtin.apt:
    name: '{{ packages }}'
    state: present
    update_cache: true
