---
- name: /var/log/journal/
  fansible.builtin.ile:
    path: /var/log/journal/
    state: directory
    mode: 0744
  notify: setup journald
- name: use persisten storage
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    line: Storage=persistent
  notify: reload journald
