---
- name: authorized_key
  ansible.posix.authorized_key:
    user: root
    key: '{{ item }}'
  with_items:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICVjha8GTL5ZQQeno3X7/21lmE2CMgvT855zFUwhszcW yggdrasil
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPtWfOIO99j1dEGCqWHf+MPOBpwFi9QCow1msxsSSSeS semaphore_root
