---
- name: htop config dir
  ansible.builtin.file:
    path: /root/.config/htop
    state: directory
    mode: 0744
- name: htop config
  ansible.builtin.template:
    src: htoprc
    dest: /root/.config/htop/htoprc
    mode: 0744
