---
- name: /var/lib/prometheus/node-exporter
  ansible.builtin.file:
    name: /var/lib/prometheus/node-exporter
    state: directory
    mode: 0744
    owner: prometheus

- name: set prometheus_services
  ansible.builtin.set_fact: prometheus_services="{{ prometheus_services+prometheus_spefic_services| default([], true) }}"

- name: prometheus packages
  ansible.builtin.apt:
    name: '{{ prometheus_services }}'

# - name: clear apt.sh
#   ansible.builtin.shell: chattr -i /usr/share/prometheus-node-exporter-collectors/apt.sh; echo "" > /usr/share/prometheus-node-exporter-collectors/apt.sh; chattr +i /usr/share/prometheus-node-exporter-collectors/apt.sh
#   ignore_errors: true

- name: textfiles_dir
  ansible.builtin.file:
    name: "{{ textfiles_dir }}"
    state: directory
    mode: 0744  
    owner: prometheus
- name: node-exporter-config
  ansible.builtin.template:
    src: prometheus-node-exporter
    dest: /etc/default/prometheus-node-exporter
    mode: 0744  
    owner: prometheus

- name: prometheus restart
  ansible.builtin.systemd:
    state: started
    name: '{{ item }}'
  with_items: '{{ prometheus_services }}'

# - name: prometheus open ports - https://github.com/prometheus/prometheus/wiki/Default-port-allocations
#   ansible.builtin.ufw:
#     rule: allow
#     port: '{{ item }}'
#     proto: tcp
#   with_items:
#     - "9100"
#     - "9104"
#     - "9113"
#     - "9122"
#     - "9147"
#     - "9187"
#     - "9227"
