---
- name: Add an apt key by id from a keyserver
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: DA418C88A3219F7B

- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64]  https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
    state: present

- name: install package
  ansible.builtin.apt:
    name: vault
    state: latest
    update_cache: yes
  notify: restart

- name: vault.hcl
  ansible.builtin.template:
    src: vault.hcl.j2
    dest: /etc/vault.d/vault.hcl
  notify: restart

- name: service
  ansible.builtin.systemd:
    name: vault
    state: started
    enabled: true

- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
