---
- name: install duplicati
  apt:
    deb: https://updates.duplicati.com/beta/duplicati_{{duplicati_ver}}_all.deb
- name: install wrapper
  get_url:
    url: https://raw.githubusercontent.com/danielskowronski/duplicati_dropbox_wrapper/master/duplicati_wrapper.sh
    dest: /opt/duplicati_wrapper.sh 
    mode: 555

- name: set up config
  template:
    src: duplicati_wrapper.conf
    dest: /etc/duplicati_wrapper.conf

- name: set up schedules
  cron:
    name: 'duplicati_{{item.path}}'
    minute: '{{item.minute}}'
    hour: '{{item.hour}}'
    job: /opt/duplicati_wrapper.sh backup {{item.path}}
  with_items: '{{duplicati_jobs}}'

- name: make sure prometheus_nodexporter is set up - param
  lineinfile:
    line: 'ARGS="$ARGS --collector.textfile.directory=/var/lib/prometheus/node-exporter"'
    path: /etc/default/prometheus
    create: true
- name: make sure prometheus_nodexporter is set up - dir
  file: 
    path: /var/lib/prometheus/node-exporter
    state: directory
    owner: prometheus
- name: make sure prometheus_nodexporter is set up - service
  systemd:
    name: prometheus-node-exporter
    state: restarted

