---
prometheus_spefic_services:
#  - prometheus-nginx-exporter
scrape_specific_logs:
  - job: nginx_access
    path: /var/log/nginx/access.log
  - job: nginx_errors
    path: /var/log/nginx/error.log
